spring.jpa:
  database: POSTGRESQL
  hibernate:
    ddl-auto: create-drop
  show-sql: true

spring.datasource:
  platform: postgres
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/inventorydb
  username: spring
  password: spring

server:
  port: 8015

eureka:
  client:
    serviceUri:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: inventory-service